name: Run Selected module Testcases
'on':
  workflow_dispatch:
    inputs:
      Module:
        description: Select Test Suite for execution
        default: 'RerunTest'
        required: true
        type: choice
        options:
          - SmokeTest
          - RegressionTest
          - RerunTest

      Browser:
        description: Select Browser for execution
        default: 'Chrome'
        required: true
        type: choice
        options:
          - Chrome
          - Edge
          - Firefox

      Environment:
        description: Select Environment for execution
        default: 'QA'
        required: true
        type: choice
        options:
          - QA
          - TEST
          - DEV
jobs:

  RunTests:

    runs-on: windows-latest

    steps: 
      - name : Chrome setup
        uses: browser-actions/setup-chrome@v1

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: adopt

      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.3
        with:
          maven-version: 3.8.2

      - name: Project Checkout
        uses: actions/checkout@master
        
      - name: Started Tests Execution
        working-directory: ./QEA-Integration-Tests
        run: 'mvn clean -DsuiteXmlFile="Run_UI_Tests.xml" -Dtags=@${{github.event.inputs.Module}} -Dbrowser=${{github.event.inputs.Browser}} test'

      - name: Started FAILED Tests Re-Run Execution
        working-directory: ./QEA-Integration-Tests
        run: 'mvn clean -DsuiteXmlFile="Run_FailedTest.xml" test'
        
      - name: Upload Execution Report
        if: '${{always()}}'
        uses: actions/upload-artifact@v3
        with:
          name: Execution-Report
          path: 'D:/a/QE-Project/QE-Project/QEA-Integration-Tests/ExtentReport'
     
      - name: Send Email
        if: success() || failure()
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.office365.com
          server_port: 587
          secure: true
          username: 'qatest1258@outlook.com'
          password: 'TestAutomation@11'
          subject: >-
            Execution of ${{ github.workflow }} has ${{ job.status }}
          body: >-
            Execution of ${{ github.workflow }} has ${{ job.status }}. Please check the attached report.
          to: 'vijayy8981@gmail.com,shivanand.jangam@gmail.com'
          from: Automated Tests Execution report for ${{github.event.inputs.Module}} Suite
          contentType: text/html
          attachments: 'D:/a/QE-Project/QE-Project/QEA-Integration-Tests/ExtentReport/FirstRunCucumberHtmlReport/ExtentHtmlReport.html'
